### ISSUE TITLE
PLEX live streaming ROKU

### ISSUE THREAD

**Issue by Harborlights** [psyciknz/NextPVR-Plex#9]
ROKU recently updated software from ver. 7.2 to 7.5. Previously live streaming worked flawlessly. Now when I attempt to stream OTA to ROKU, I get an error message "Video not available" All other functions operating without issue. Live streaming works on Amazon FireTV Stick without issue.

**Comment by psyciknz** [comment]
I don't think it's the roku.   Does using the web Player work?  I assume you're on the latest plex server?  I think that broke it.  I haven't figured out why yet.

**Comment by Harborlights** [comment]
Web player streaming no problem. Amazon FireTV Stick streaming no 
problem. ROKU VER. 7.2 streamed no problem. ROKU VER. 7.5 recording 
playback works but live streaming does not work. ROKU made changes to 
transcoding in most recent update. There are no server problems as I 
can  play other PLEX channels (NBC, CBS, ABC).

When I attempt to play a live channel the interface starts and appears 
to be loading but before the stream appears I get an error message 
saying "Video Unavailable" " "We are unable to play this video. Make 
sure the server is running and the video is available"

This is the only problem I have ever had with your application. Yes 
latest PLEX sever.

**Comment by Harborlights** [comment]
PLEX made changes to transcoding in most recent update not ROKU as 
stated below. But I was having problems before the most recent PLEX 
update and PLEX plays live streaming in amazon fire TV stick without 
problems.

**Comment by psyciknz** [comment]
Hmm I lost streaming via NextPVR via Web Player, Apple TV and Roku on last server upgrade.
